/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type ListModule = {
  _type: "listModule";
  heading: string;
  items: string;
};

export type SliderModule = {
  _type: "sliderModule";
  items?: Array<{
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    heading: string;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "sliderItem";
    _key: string;
  }>;
};

export type TextModule = {
  _type: "textModule";
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SplitTextModule = {
  _type: "splitTextModule";
  headingLeft?: string;
  bodyLeft?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  headingRight?: string;
  bodyRight?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type VideoModule = {
  _type: "videoModule";
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type HeroModule = {
  _type: "heroModule";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heading?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SimplePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ComplexPortableText = Array<{
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
  _key: string;
} | {
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "h2" | "h3" | "h4" | "normal" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    _key: string;
  } & Link>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Link = {
  _type: "link";
  title?: string;
  linkType: "page" | "url";
  page?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "homepage";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "online";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "offline";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "textPage";
  };
  url?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  rows?: Array<{
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    text: SimplePortableText;
    _type: "row";
    _key: string;
  }>;
};

export type FooterSettings = {
  _id: string;
  _type: "footerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heading?: string;
  items?: Array<string>;
  email?: string;
  nav?: Array<{
    _key: string;
  } & Link>;
};

export type HeaderSettings = {
  _id: string;
  _type: "headerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  leftNav?: Array<{
    _key: string;
  } & Link>;
  rightNav?: Array<{
    _key: string;
  } & Link>;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from: string;
  to?: string;
  isPermanent?: boolean;
};

export type TextPage = {
  _id: string;
  _type: "textPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: ComplexPortableText;
  seo?: Seo;
};

export type Offline = {
  _id: string;
  _type: "offline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
  seo?: Seo;
};

export type Online = {
  _id: string;
  _type: "online";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  modules?: Array<{
    _key: string;
  } & TextModule | {
    _key: string;
  } & VideoModule | {
    _key: string;
  } & SliderModule | {
    _key: string;
  } & ListModule>;
  seo?: Seo;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  modules?: Array<{
    _key: string;
  } & HeroModule | {
    _key: string;
  } & VideoModule | {
    _key: string;
  } & SplitTextModule>;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Site = {
  _id: string;
  _type: "site";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  URL?: string;
  gtmID?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Seo = {
  _type: "seo";
  title: string;
  description?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    _key: string;
  } & SanityAssistInstructionFieldRef | {
    _key: string;
  } & SanityAssistInstructionContext | {
    _key: string;
  } & SanityAssistInstructionUserInput>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    _key: string;
  } & SanityAssistOutputField | {
    _key: string;
  } & SanityAssistOutputType>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | ListModule | SliderModule | TextModule | SplitTextModule | VideoModule | HeroModule | SimplePortableText | ComplexPortableText | Link | Project | FooterSettings | HeaderSettings | Redirect | TextPage | Offline | Online | Homepage | Slug | Site | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Seo | SanityAssistInstructionTask | SanityAssistTaskStatus | SanityAssistSchemaTypeAnnotations | SanityAssistOutputType | SanityAssistOutputField | SanityAssistInstructionContext | AssistInstructionContext | SanityAssistInstructionUserInput | SanityAssistInstructionPrompt | SanityAssistInstructionFieldRef | SanityAssistInstruction | SanityAssistSchemaTypeField;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_id == "site"][0]{  ...,  title,  URL,  gtmID,  seo{      ...,  metaTitle,  metaDesc,  shareTitle,  shareDesc,  shareGraphic  }}
export type SettingsQueryResult = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  URL: null;
  gtmID: null;
  seo: null;
} | {
  _id: string;
  _type: "footerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heading?: string;
  items?: Array<string>;
  email?: string;
  nav?: Array<{
    _key: string;
  } & Link>;
  title: null;
  URL: null;
  gtmID: null;
  seo: null;
} | {
  _id: string;
  _type: "headerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  leftNav?: Array<{
    _key: string;
  } & Link>;
  rightNav?: Array<{
    _key: string;
  } & Link>;
  title: null;
  URL: null;
  gtmID: null;
  seo: null;
} | {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug?: Slug;
  modules?: Array<{
    _key: string;
  } & HeroModule | {
    _key: string;
  } & SplitTextModule | {
    _key: string;
  } & VideoModule>;
  seo: {
    _type: "seo";
    title: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      metadataBase?: string;
      _type: "image";
    };
    metaTitle: null;
    metaDesc: null;
    shareTitle: null;
    shareDesc: null;
    shareGraphic: null;
  } | null;
  URL: null;
  gtmID: null;
} | {
  _id: string;
  _type: "offline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug?: Slug;
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
  seo: {
    _type: "seo";
    title: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      metadataBase?: string;
      _type: "image";
    };
    metaTitle: null;
    metaDesc: null;
    shareTitle: null;
    shareDesc: null;
    shareGraphic: null;
  } | null;
  URL: null;
  gtmID: null;
} | {
  _id: string;
  _type: "online";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug?: Slug;
  modules?: Array<{
    _key: string;
  } & ListModule | {
    _key: string;
  } & SliderModule | {
    _key: string;
  } & TextModule | {
    _key: string;
  } & VideoModule>;
  seo: {
    _type: "seo";
    title: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      metadataBase?: string;
      _type: "image";
    };
    metaTitle: null;
    metaDesc: null;
    shareTitle: null;
    shareDesc: null;
    shareGraphic: null;
  } | null;
  URL: null;
  gtmID: null;
} | {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  rows?: Array<{
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    text: SimplePortableText;
    _type: "row";
    _key: string;
  }>;
  URL: null;
  gtmID: null;
  seo: null;
} | {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from: string;
  to?: string;
  isPermanent?: boolean;
  title: null;
  URL: null;
  gtmID: null;
  seo: null;
} | {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title: string | null;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
  URL: null;
  gtmID: null;
  seo: null;
} | {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title: string | null;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
  URL: null;
  gtmID: null;
  seo: null;
} | {
  _id: string;
  _type: "site";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  URL: string | null;
  gtmID: string | null;
  seo: {
    _type: "seo";
    title: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      metadataBase?: string;
      _type: "image";
    };
    metaTitle: null;
    metaDesc: null;
    shareTitle: null;
    shareDesc: null;
    shareGraphic: null;
  } | null;
} | {
  _id: string;
  _type: "textPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug?: Slug;
  body?: ComplexPortableText;
  seo: {
    _type: "seo";
    title: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      metadataBase?: string;
      _type: "image";
    };
    metaTitle: null;
    metaDesc: null;
    shareTitle: null;
    shareDesc: null;
    shareGraphic: null;
  } | null;
  URL: null;
  gtmID: null;
} | null;
// Variable: layoutQuery
// Query: {  "header": *[_id == "headerSettings"][0]{      ...,  leftNav[]{      ...,    page->{    "type": _type,    "slug": slug.current,    "isHome": _id==homepage,  }  },  rightNav[]{      ...,    page->{    "type": _type,    "slug": slug.current,    "isHome": _id==homepage,  }  },  logo  },  "footer": *[_id == "footerSettings"][0]{      logo,  heading,  email,  items,  nav[]{      ...,    page->{    "type": _type,    "slug": slug.current,    "isHome": _id==homepage,  }  }  }}
export type LayoutQueryResult = {
  header: {
    _id: string;
    _type: "assist.instruction.context";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    context?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "footerSettings";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    logo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    heading?: string;
    items?: Array<string>;
    email?: string;
    nav?: Array<{
      _key: string;
    } & Link>;
    leftNav: null;
    rightNav: null;
  } | {
    _id: string;
    _type: "headerSettings";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    leftNav: Array<{
      _key: string;
      _type: "link";
      title?: string;
      linkType: "page" | "url";
      page: {
        type: "homepage";
        slug: string | null;
        isHome: false;
      } | {
        type: "offline";
        slug: string | null;
        isHome: false;
      } | {
        type: "online";
        slug: string | null;
        isHome: false;
      } | {
        type: "textPage";
        slug: string | null;
        isHome: false;
      } | null;
      url?: string;
    }> | null;
    rightNav: Array<{
      _key: string;
      _type: "link";
      title?: string;
      linkType: "page" | "url";
      page: {
        type: "homepage";
        slug: string | null;
        isHome: false;
      } | {
        type: "offline";
        slug: string | null;
        isHome: false;
      } | {
        type: "online";
        slug: string | null;
        isHome: false;
      } | {
        type: "textPage";
        slug: string | null;
        isHome: false;
      } | null;
      url?: string;
    }> | null;
    logo: null;
  } | {
    _id: string;
    _type: "homepage";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    modules?: Array<{
      _key: string;
    } & HeroModule | {
      _key: string;
    } & SplitTextModule | {
      _key: string;
    } & VideoModule>;
    seo?: Seo;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "offline";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    projects?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "project";
    }>;
    seo?: Seo;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "online";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    modules?: Array<{
      _key: string;
    } & ListModule | {
      _key: string;
    } & SliderModule | {
      _key: string;
    } & TextModule | {
      _key: string;
    } & VideoModule>;
    seo?: Seo;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "project";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    rows?: Array<{
      images: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      text: SimplePortableText;
      _type: "row";
      _key: string;
    }>;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "redirect";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    from: string;
    to?: string;
    isPermanent?: boolean;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "sanity.fileAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "site";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    URL?: string;
    gtmID?: string;
    seo?: Seo;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | {
    _id: string;
    _type: "textPage";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    body?: ComplexPortableText;
    seo?: Seo;
    leftNav: null;
    rightNav: null;
    logo: null;
  } | null;
  footer: {
    logo: null;
    heading: null;
    email: null;
    items: null;
    nav: null;
  } | {
    logo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    heading: string | null;
    email: string | null;
    items: Array<string> | null;
    nav: Array<{
      _key: string;
      _type: "link";
      title?: string;
      linkType: "page" | "url";
      page: {
        type: "homepage";
        slug: string | null;
        isHome: false;
      } | {
        type: "offline";
        slug: string | null;
        isHome: false;
      } | {
        type: "online";
        slug: string | null;
        isHome: false;
      } | {
        type: "textPage";
        slug: string | null;
        isHome: false;
      } | null;
      url?: string;
    }> | null;
  } | null;
};
// Variable: homeQuery
// Query: *[_type == "homepage" && _id ==  "homepage" ][0]{  ...,  "isHome": _id==homepage,  modules[]{      _type == 'splitTextModule' => {    ...  },  _type == 'videoModule' => {    ...,    image,    video,  },  _type == 'textModule' => {    ...  },  _type == 'listModule' => {    ...  },  _type == 'heroModule' => {    ...,    image,  },  _type == 'sliderModule' => {    ...,    items[] {      image,      body    }  }  }}
export type HomeQueryResult = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  modules: Array<{
    _key: string;
    _type: "heroModule";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    heading?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "splitTextModule";
    headingLeft?: string;
    bodyLeft?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    headingRight?: string;
    bodyRight?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "videoModule";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  }> | null;
  seo?: Seo;
  isHome: false;
} | null;
// Variable: onlineQuery
// Query: *[_type == "online" && _id ==  "online" ][0]{  ...,  "isHome": _id==homepage,  modules[]{      _type == 'splitTextModule' => {    ...  },  _type == 'videoModule' => {    ...,    image,    video,  },  _type == 'textModule' => {    ...  },  _type == 'listModule' => {    ...  },  _type == 'heroModule' => {    ...,    image,  },  _type == 'sliderModule' => {    ...,    items[] {      image,      body    }  }  }}
export type OnlineQueryResult = {
  _id: string;
  _type: "online";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  modules: Array<{
    _key: string;
    _type: "listModule";
    heading: string;
    items: string;
  } | {
    _key: string;
    _type: "sliderModule";
    items: Array<{
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      body: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }>;
    }> | null;
  } | {
    _key: string;
    _type: "textModule";
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
  } | {
    _key: string;
    _type: "videoModule";
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    video: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  }> | null;
  seo?: Seo;
  isHome: false;
} | null;
// Variable: offlineQuery
// Query: *[_type == "offline" && _id ==  "offline" ][0]{  ...,  projects[]->{      _type,  _id,  slug,  title,  year,  rows[]  }}
export type OfflineQueryResult = {
  _id: string;
  _type: "offline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  projects: Array<{
    _type: "project";
    _id: string;
    slug: null;
    title: string;
    year: null;
    rows: Array<{
      images: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      text: SimplePortableText;
      _type: "row";
      _key: string;
    }> | null;
  }> | null;
  seo?: Seo;
} | null;
// Variable: allTextPagesQuery
// Query: *[_type == "textPage" && defined(slug.current)] | order(date desc, _updatedAt desc) {    "slug": slug.current  }
export type AllTextPagesQueryResult = Array<{
  slug: string | null;
}>;
// Variable: getTextPageQuery
// Query: *[_type == "textPage" && slug.current == $slug] [0] {    _id,    _type,    title,    slug,    body[]{      ...,      markDefs[]{        ...,          page->{    "type": _type,    "slug": slug.current,    "isHome": _id==homepage,  }      }    },    seo{  ...,  metaTitle,  metaDesc,  shareTitle,  shareDesc,  shareGraphic}  }
export type GetTextPageQueryResult = {
  _id: string;
  _type: "textPage";
  title: string | null;
  slug: Slug | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs: Array<{
      _key: string;
      _type: "link";
      title?: string;
      linkType: "page" | "url";
      page: {
        type: "homepage";
        slug: string | null;
        isHome: false;
      } | {
        type: "offline";
        slug: string | null;
        isHome: false;
      } | {
        type: "online";
        slug: string | null;
        isHome: false;
      } | {
        type: "textPage";
        slug: string | null;
        isHome: false;
      } | null;
      url?: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
    markDefs: null;
  }> | null;
  seo: {
    _type: "seo";
    title: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      metadataBase?: string;
      _type: "image";
    };
    metaTitle: null;
    metaDesc: null;
    shareTitle: null;
    shareDesc: null;
    shareGraphic: null;
  } | null;
} | null;
// Variable: textPagesSlugs
// Query: *[_type == "textPage" && defined(slug.current)]  {"slug": slug.current}
export type TextPagesSlugsResult = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_id == \"site\"][0]{\n  ...,\n  title,\n  URL,\n  gtmID,\n  seo{\n    \n  ...,\n  metaTitle,\n  metaDesc,\n  shareTitle,\n  shareDesc,\n  shareGraphic\n\n  }\n}": SettingsQueryResult;
    "{\n  \"header\": *[_id == \"headerSettings\"][0]{\n    \n  ...,\n  leftNav[]{\n    \n  ...,\n  \n  page->{\n    \"type\": _type,\n    \"slug\": slug.current,\n    \"isHome\": _id==homepage,\n  }\n\n\n  },\n  rightNav[]{\n    \n  ...,\n  \n  page->{\n    \"type\": _type,\n    \"slug\": slug.current,\n    \"isHome\": _id==homepage,\n  }\n\n\n  },\n  logo\n\n  },\n  \"footer\": *[_id == \"footerSettings\"][0]{\n    \n  logo,\n  heading,\n  email,\n  items,\n  nav[]{\n    \n  ...,\n  \n  page->{\n    \"type\": _type,\n    \"slug\": slug.current,\n    \"isHome\": _id==homepage,\n  }\n\n\n  }\n\n  }\n}": LayoutQueryResult;
    "*[_type == \"homepage\" && _id ==  \"homepage\" ][0]{\n  ...,\n  \"isHome\": _id==homepage,\n  modules[]{\n    \n  _type == 'splitTextModule' => {\n    ...\n  },\n  _type == 'videoModule' => {\n    ...,\n    image,\n    video,\n  },\n  _type == 'textModule' => {\n    ...\n  },\n  _type == 'listModule' => {\n    ...\n  },\n  _type == 'heroModule' => {\n    ...,\n    image,\n  },\n  _type == 'sliderModule' => {\n    ...,\n    items[] {\n      image,\n      body\n    }\n  }\n\n  }\n}": HomeQueryResult;
    "*[_type == \"online\" && _id ==  \"online\" ][0]{\n  ...,\n  \"isHome\": _id==homepage,\n  modules[]{\n    \n  _type == 'splitTextModule' => {\n    ...\n  },\n  _type == 'videoModule' => {\n    ...,\n    image,\n    video,\n  },\n  _type == 'textModule' => {\n    ...\n  },\n  _type == 'listModule' => {\n    ...\n  },\n  _type == 'heroModule' => {\n    ...,\n    image,\n  },\n  _type == 'sliderModule' => {\n    ...,\n    items[] {\n      image,\n      body\n    }\n  }\n\n  }\n}": OnlineQueryResult;
    "*[_type == \"offline\" && _id ==  \"offline\" ][0]{\n  ...,\n  projects[]->{\n    \n  _type,\n  _id,\n  slug,\n  title,\n  year,\n  rows[]\n\n  }\n}": OfflineQueryResult;
    "\n  *[_type == \"textPage\" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \"slug\": slug.current\n  }\n": AllTextPagesQueryResult;
    "\n  *[_type == \"textPage\" && slug.current == $slug] [0] {\n    _id,\n    _type,\n    title,\n    slug,\n    body[]{\n      ...,\n      markDefs[]{\n        ...,\n        \n  page->{\n    \"type\": _type,\n    \"slug\": slug.current,\n    \"isHome\": _id==homepage,\n  }\n\n      }\n    },\n    seo{\n  ...,\n  metaTitle,\n  metaDesc,\n  shareTitle,\n  shareDesc,\n  shareGraphic\n}\n  }\n": GetTextPageQueryResult;
    "\n  *[_type == \"textPage\" && defined(slug.current)]\n  {\"slug\": slug.current}\n": TextPagesSlugsResult;
  }
}
